WebUI/Controllers/RolodexController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class RolodexController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public RolodexController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Contacts()
        {
            var people = new List<PersonViewModel>();
            var values = GetContacts().Result;
            if(values != null)
            foreach( var contact in values)
            {
                people.Add(contact);
            }
            return View(people);
        }

        public IActionResult AddOrEditContact()
        {
            return View();
        }

        public IActionResult AddContact()
        {
            var person = new PersonViewModel();
            person.PhysicalAddresses.Add(new() { StreetAddress = "" });
            person.PhoneNumbers.Add(new() { Number = "" });
            person.EmailAddresses.Add(new() { Email = "" });
            return View(person);
        }

        [HttpPost]
        public async Task<IActionResult> AddContactAsync(PersonViewModel person)
        {
            string url = "https://localhost:7228/api/Rolodex/Contact";
            var content = new StringContent(JsonSerializer.Serialize(person), Encoding.UTF8, "application/json");

            var httpClient = _httpClientFactory.CreateClient();
            var httpResponseMessage = await httpClient.PostAsync(url, content);

            if (httpResponseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Contacts");
            }

            return RedirectToAction("Contacts");
        }

        public async Task<List<PersonViewModel>?> GetContacts()
        {
            string url = "https://localhost:7228/api/Rolodex/Contacts";
            List<PersonViewModel>? people = null;

            var httpClient = _httpClientFactory.CreateClient();

            var httpResponseMessage = await httpClient.GetAsync(url);

            Console.WriteLine($"Response: {httpResponseMessage.StatusCode}");

            if(httpResponseMessage.IsSuccessStatusCode)
            {
                var contentStream = await httpResponseMessage.Content.ReadAsStreamAsync();
                var options = new JsonSerializerOptions()
                {
                    ReferenceHandler = ReferenceHandler.Preserve,
                    WriteIndented = true
                };
                people = await JsonSerializer.DeserializeAsync<List<PersonViewModel>>(contentStream, options);
            }

            return people;
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            string url = $"https://localhost:7228/api/Rolodex/Contact?id={id}";
            PersonViewModel? person = new();

            var httpClient = _httpClientFactory.CreateClient();

            var httpResponseMessage = await httpClient.GetAsync(url);

            Console.WriteLine($"Response: {httpResponseMessage.StatusCode}");

            if (httpResponseMessage.IsSuccessStatusCode)
            {
                var contentStream = await httpResponseMessage.Content.ReadAsStreamAsync();
                var options = new JsonSerializerOptions()
                {
                    ReferenceHandler = ReferenceHandler.Preserve,
                    WriteIndented = true
                };
                person = await JsonSerializer.DeserializeAsync<PersonViewModel>(contentStream, options);
            }
            return View(person);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            string url = $"https://localhost:7228/api/Rolodex/Contact?id={id}";
            var httpClient = _httpClientFactory.CreateClient();

            await httpClient.DeleteAsync(url);

            return RedirectToAction("Contacts");
        }

        public async Task<IActionResult> EditContact(int id)
        {
            string url = $"https://localhost:7228/api/Rolodex/Contact?id={id}";
            PersonViewModel? person = new();

            var httpClient = _httpClientFactory.CreateClient();

            var httpResponseMessage = await httpClient.GetAsync(url);

            Console.WriteLine($"Response: {httpResponseMessage.StatusCode}");

            if (httpResponseMessage.IsSuccessStatusCode)
            {
                var contentStream = await httpResponseMessage.Content.ReadAsStreamAsync();
                var options = new JsonSerializerOptions()
                {
                    ReferenceHandler = ReferenceHandler.Preserve,
                    WriteIndented = true
                };
                person = await JsonSerializer.DeserializeAsync<PersonViewModel>(contentStream, options);
            }
            return View(person);
        }

        [HttpPost]
        public async Task<IActionResult> EditContactAsync(PersonViewModel person)
        {
            var url = $"https://localhost:7228/api/Rolodex/Contact?id={person.Id}";
            var content = new StringContent(JsonSerializer.Serialize(person), Encoding.UTF8, "application/json");
            var httpClient = _httpClientFactory.CreateClient();

            var httpResponseMessage = await httpClient.PutAsync(url, content);

            if (httpResponseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Contacts");
            }

            return RedirectToAction("Contacts");
        }

        [HttpGet]
        public ActionResult AddAddress(int id)
        {
            var address = new PhysicalAddressViewModel()
            {
                PersonId = id
            };

            return View(address);
        }

        [HttpPost]
        public async Task<IActionResult> AddAddressAsync(PhysicalAddressViewModel address)
        {
            var url = $"https://localhost:7228/api/Rolodex/Address";
            var content = new StringContent(JsonSerializer.Serialize(address), Encoding.UTF8, "application/json");
            var httpClient = _httpClientFactory.CreateClient();

            await httpClient.PostAsync(url, content);

            return RedirectToAction("Contacts");
        }

        [HttpGet]
        public ActionResult AddEmail(int id)
        {
            var address = new EmailAddressViewModel()
            {
                PersonId = id
            };

            return View(address);
        }

        [HttpPost]
        public async Task<IActionResult> AddEmailAsync(EmailAddressViewModel address)
        {
            var url = $"https://localhost:7228/api/Rolodex/Email";
            var content = new StringContent(JsonSerializer.Serialize(address), Encoding.UTF8, "application/json");
            var httpClient = _httpClientFactory.CreateClient();

            await httpClient.PostAsync(url, content);

            return RedirectToAction("Contacts");
        }

        [HttpGet]
        public ActionResult AddPhone(int id)
        {
            var number = new PhoneNumberViewModel()
            {
                PersonId = id
            };

            return View(number);
        }

        [HttpPost]
        public async Task<IActionResult> AddPhoneAsync(PhoneNumberViewModel phoneNumber)
        {
            var url = $"https://localhost:7228/api/Rolodex/Phone";
            var content = new StringContent(JsonSerializer.Serialize(phoneNumber), Encoding.UTF8, "application/json");
            var httpClient = _httpClientFactory.CreateClient();

            await httpClient.PostAsync(url, content);

            return RedirectToAction("Contacts");
        }
    }
}

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rolodex</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div style="text-align:left">
                    <img src="@Url.Content("~/Images/GpNew.png")" height="45" width="190" />
                </div>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rolodex</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Rolodex" asp-action="Contacts">Contacts List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>